#
# Common tasks for product deployment
#
---
- name: Preparing and starting all vagrant instances for develop environment
  command: vagrant up chdir="~/prj/BEAM/{{ BEAM_VARS.PRODUCT.REPO_NAME }}/demo/vagrant-instances/develop/{{ item }}"
  with_items:
    - all-in-one-instance
  when: BEAM_VARS.PRODUCT.ENVIRONMENT=="develop"

- name: Preparing and starting all vagrant instances for production environment
  command: vagrant up chdir="~/prj/BEAM/{{ BEAM_VARS.PRODUCT.REPO_NAME }}/demo/vagrant-instances/production/{{ item }}"
  with_items:
    - db
    - backend
    - frontend
  when: BEAM_VARS.PRODUCT.ENVIRONMENT=="production"
